spring:
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: false
    hibernate:
      ddl-auto: update
    open-in-view: 'false'
  mvc:
    hiddenmethod:
      filter:
        enabled: 'true'
  datasource:
    url: jdbc:mysql://localhost:3306/reseller?allowPublicKeyRetrieval=true&useSSL=false&createDatabaseIfNotExist=true&serverTimezone=UTC
    driverClassName: com.mysql.cj.jdbc.Driver
    username: 'root'
    password: '1234'
logging:
  level:
    org:
      hibernate:
        type:
          descriptor: TRACE
        SQL: DEBUG
      nodeValue: WARN
    blog: WARN
server:
  port: 8080
