spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${MYSQL_HOST:localhost}:3306/expiration_date_manager?allowPublicKeyRetrieval=true&useSSL=false&createDatabaseIfNotExist=true&serverTimezone=UTC&useUnicode=true&characterEncoding=UTF-8
    username: ${MYSQL_USER:root}
    password: ${MYSQL_PASS:1234}
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 25MB
  mvc:
    hiddenmethod:
      filter:
        enabled: true
  #  sql:
  #    init:
  #      mode: always
  jpa:
    # Choose either MySQL 8 or MySQL 5 below
    # For MySQL 8
    database-platform: org.hibernate.dialect.MySQL8Dialect
    #For MySQL 5
    #    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: update
    open-in-view: false
    properties:
      hibernate:
        format_sql: false
        show_sql: true
    defer-datasource-initialization: true
# Cloudinary Properties
expirationManager:
  cloudinary:
    cloud-name: ${CLOUD_NAME}
    api-key: ${API_KEY}
    api-secret: ${API_SECRET}
# Custom properties
  default:
    password: ${DEFAULT_PASS:123456}
    mailDomain: ${DEFAULT_DOMAIN:@email.email}
